/*
 * xp_streamdeck - Stream Deck plugin for X-Plane 12
 * Copyright (c) 2026 thWelly
 *
 * Licensed under the MIT License.
 * See the LICENSE file in the project root for full license text.
 */

// Action-specific helpers — depends on Stream Deck SDK action types and is
// only meant to be consumed from src/actions/.
import streamDeck, { type DialAction, type KeyAction } from "@elgato/streamdeck";
import type { JsonObject } from "@elgato/utils";

export const NOT_FOUND_SUFFIX = "?";

// Bundle-local path (relative to com.robertw.xplane.sdPlugin/) generated by
// scripts/generate-icons.ts on every `make icons` run.
export const OFFLINE_IMAGE = "imgs/sim_offline";

/**
 * Stack a user-provided title on top of a status/value suffix. Returning the
 * combined string lets each action call setTitle() once, preserving the label
 * the user typed in Stream Deck's Title field.
 */
export function combineTitle(userTitle: string, suffix: string): string {
	if (!userTitle) return suffix;
	if (!suffix) return userTitle;
	return `${userTitle}\n${suffix}`;
}

export function setNotFound<T extends JsonObject>(action: KeyAction<T>, label = ""): Promise<void> {
	return action.setTitle(combineTitle(label, NOT_FOUND_SUFFIX)).catch((err) => {
		streamDeck.logger.warn("error-tile: setTitle not-found failed", err);
	});
}

export function clearTile<T extends JsonObject>(action: KeyAction<T>, label = ""): Promise<void> {
	return action.setTitle(label).catch((err) => {
		streamDeck.logger.warn("error-tile: clearTitle failed", err);
	});
}

/**
 * Replaces the action's image with the bundle-local "SIM OFFLINE" placeholder
 * and clears the title so the placeholder isn't covered by leftover labels
 * or live values. Used by every action when the X-Plane connection has been
 * absent long enough for the client to emit "offline".
 *
 * No-op for DialActions — the offline placeholder is designed for the 144×144
 * key bitmap. Encoders show their offline state on the touch strip instead,
 * via setDialFeedback(..., "OFFLINE") in src/actions/encoder.ts.
 */
export async function setOffline<T extends JsonObject>(
	action: KeyAction<T> | DialAction<T>,
): Promise<void> {
	if (!action.isKey()) return;
	try {
		await action.setImage(OFFLINE_IMAGE);
	} catch (err) {
		streamDeck.logger.warn("error-tile: setImage offline failed", err);
	}
	try {
		await action.setTitle("");
	} catch (err) {
		streamDeck.logger.warn("error-tile: setTitle offline-clear failed", err);
	}
}

/**
 * Restores the action's default image (the one the user dropped onto the key
 * in the Stream Deck app, or the manifest fallback). Title handling is left
 * to the caller — most actions re-render their title from live data on the
 * next subscription tick.
 */
export async function clearOffline<T extends JsonObject>(
	action: KeyAction<T> | DialAction<T>,
): Promise<void> {
	if (!action.isKey()) return;
	try {
		await action.setImage();
	} catch (err) {
		streamDeck.logger.warn("error-tile: setImage clear-offline failed", err);
	}
}
